// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import <Foundation/Foundation.h>
@class TSHelloWorld;


@interface TSHelloWorld : NSObject

+ (nullable TSHelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

@end
