export const GET_ACCOUNT = 'GET_ACCOUNT'
export const CREATE_NEW_ACCOUNT = 'CREATE_NEW_ACCOUNT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const ADD_PHONE = 'ADD_PHONE'
export const ERROR = 'ERROR'
export const PRIMARY_COLOR = '#FF4500'
export const FONT_FAMILY = '#FF4500'
export const LINK = 'https://orbyt.herokuapp.com/'