# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Orbyt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orbyt

  target 'Orbyt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  end

  target 'OrbytTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Orbyt-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orbyt-tvOS

  #target 'Orbyt-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end
